server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: cpu-top-demo
  
  # 日志配置
  logging:
    level:
      com.example.cputopdemo: DEBUG
      root: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true

# 应用信息
info:
  app:
    name: CPU Top Demo
    description: SpringBoot项目用于模拟CPU飙升导致服务无响应
    version: 1.0.0
    author: 开发者 